apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      nodeSelector:
        nodepoolcolor: green
        nodepoolmode: user
      containers:
      - image: nginxdemos/hello
        name: nginx-green
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "350m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-green-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-green
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-green-ing
  annotations:
    kubernetes.io/ingress.class: green
    nginx.ingress.kubernetes.io/ingress.class: green
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
       paths:
       - backend:
           serviceName: nginx-green-svc
           servicePort: 80
         path: /(/|$)(.*)
       - backend:
           serviceName: nginx-green-svc
           servicePort: 80
         path: /nginx(/|$)(.*)
